### ISSUE TITLE
S3 lookup tables no longer available

### ISSUE THREAD

**Issue by AlLoeser** [dwalton76/rubiks-cube-NxNxN-solver#91] opened 2021-12-17 14:00 UTC
Hi - I've been messing around with this great work, but the S3 lookup tables are no longer available.  Are you going to restore access to those, or publish the table building code?

--2021-12-17 08:49:09--  https://rubiks-cube-lookup-tables.s3.amazonaws.com/lookup-table-6x6x6-step50-LR-solve-inner-x-center-and-oblique-edges.bin.gz
Resolving rubiks-cube-lookup-tables.s3.amazonaws.com (rubiks-cube-lookup-tables.s3.amazonaws.com)... 54.231.133.97
Connecting to rubiks-cube-lookup-tables.s3.amazonaws.com (rubiks-cube-lookup-tables.s3.amazonaws.com)|54.231.133.97|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-12-17 08:49:09 ERROR 403: Forbidden.

Traceback (most recent call last):
  File "./rubiks-cube-solver.py", line 124, in <module>
    cube.solve(solution333)
  File "/Users/alloeser/rubiks-cube-NxNxN-solver/rubikscubennnsolver/__init__.py", line 4648, in solve
    self.reduce_333()
  File "/Users/alloeser/rubiks-cube-NxNxN-solver/rubikscubennnsolver/__init__.py", line 4557, in reduce_333
    self.reduce_555()
  File "/Users/alloeser/rubiks-cube-NxNxN-solver/rubikscubennnsolver/RubiksCubeNNNEven.py", line 254, in reduce_555
    self.make_plus_sign()
  File "/Users/alloeser/rubiks-cube-NxNxN-solver/rubikscubennnsolver/RubiksCubeNNNEven.py", line 132, in make_plus_sign
    fake_666 = self.get_fake_666()
  File "/Users/alloeser/rubiks-cube-NxNxN-solver/rubikscubennnsolver/RubiksCubeNNNEven.py", line 107, in get_fake_666
    self.fake_666.lt_init()
  File "/Users/alloeser/rubiks-cube-NxNxN-solver/rubikscubennnsolver/RubiksCube666.py", line 1659, in lt_init
    self.lt_LR_centers = LookupTable666Step50LRCenters(self)
  File "/Users/alloeser/rubiks-cube-NxNxN-solver/rubikscubennnsolver/RubiksCube666.py", line 1017, in __init__
    LookupTable.__init__(
  File "/Users/alloeser/rubiks-cube-NxNxN-solver/rubikscubennnsolver/LookupTable.py", line 550, in __init__
    download_file_if_needed(self.filename_bin)
  File "/Users/alloeser/rubiks-cube-NxNxN-solver/rubikscubennnsolver/LookupTable.py", line 445, in download_file_if_needed
    raise Exception(f"failed to download {filename_gz} via {url}")
Exception: failed to download lookup-tables/lookup-table-6x6x6-step50-LR-solve-inner-x-center-and-oblique-edges.bin.gz via https://rubiks-cube-lookup-tables.s3.amazonaws.com/lookup-table-6x6x6-step50-LR-solve-inner-x-center-and-oblique-edges.bin.gz

**Comment by ChaseOSDeveloper** [comment] 2021-12-18 00:06
hey same

**Comment by dwalton76** [comment] 2021-12-18 00:11
I can reproduce it...AWS much have changed something on me...looking

**Comment by ChaseOSDeveloper** [comment] 2021-12-18 00:12
thank you so much i really want to make something with his

**Comment by ChaseOSDeveloper** [comment] 2021-12-18 00:24
did you find anything?

**Comment by dwalton76** [comment] 2021-12-18 00:24
I see what the problem is, I got a new credit card recently and canceled my old one but forgot to update my payment method in AWS so they suspended my account.  I've paid the bill, now to wait (hopefully not too long) for AWS to reactivate my account.

**Comment by ChaseOSDeveloper** [comment] 2021-12-18 00:25
how long is it estimated we wait?

**Comment by dwalton76** [comment] 2021-12-18 00:26
Found this https://aws.amazon.com/premiumsupport/knowledge-center/reactivate-suspended-account/
`Sometimes account services can take up to 24 hours to reactivate an account`

Hopefully sooner but sounds like worst case is 24 hours.

**Comment by ChaseOSDeveloper** [comment] 2021-12-18 00:28
lets hope its like 1-3 hours

**Comment by ChaseOSDeveloper** [comment] 2021-12-18 00:31
it seems as it will take a few minutes
"If you paid your past due charges in full with a credit card, then services automatically reactivate within a few minutes."

**Comment by ChaseOSDeveloper** [comment] 2021-12-18 00:47
hey for now, may you give us txt the txt files in a zip

**Comment by dwalton76** [comment] 2021-12-18 00:50
The lookup tables are several gigs of data, I don't have anywhere else to host them thus the use of AWS.

**Comment by ChaseOSDeveloper** [comment] 2021-12-18 00:51
oh right. they are some big files

**Comment by ChaseOSDeveloper** [comment] 2021-12-18 01:39
hey

**Comment by ChaseOSDeveloper** [comment] 2021-12-18 01:39
is it up again

**Comment by ChaseOSDeveloper** [comment] 2021-12-18 16:01
what is the status of the aws

**Comment by ChaseOSDeveloper** [comment] 2021-12-18 16:41
it works now i think you can close this

**Closed** 2021-12-20 01:48 UTC
